name: CI

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "--from markdown --to html --css ./core-styles.css --lua-filter ./pagebreak.lua -o foo.html --standalone index.md"
