name: CI

on: [push]

jobs:
  convert_to_html_for_pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Create output directory
        run: mkdir output && cp styles.css output
      - name: Create HTML file from .md
        uses: docker://pandoc/core:2.9
        with:
          args: "--from markdown --to html --css ./styles.css --lua-filter ./pagebreak.lua -o output/index.html --standalone index.md"
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Deploy to pages branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: output

  convert_to_pdf:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Create output directory
        run: mkdir output
      - name: Create PDF file from .md
        uses: docker://pandoc/core:2.9
        with:
          args: "--from markdown --to pdf -t html --css ./styles.css --lua-filter ./pagebreak.lua -o output/cv.pdf --standalone index.md"
      - uses: actions/upload-artifact@v1
        with:
          name: CV
          path: output/cv.pdf
