name: CI

on: [push]

jobs:
  convert_to_html_for_pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Create output directory
        run: mkdir output && cp styles.css output
      - name: Create HTML file from .md
        uses: docker://pandoc/core:2.9
        with:
          args: "--from markdown --to html --css ./styles.css --lua-filter ./pagebreak.lua -o output/index.html --standalone index.md"
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Deploy to pages branch
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: output

  convert_to_pdf:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install pandoc and wkhtmltopdf
        run: |
          sudo apt update
          sudo apt install -y pandoc wget fontconfig fontconfig-config fonts-dejavu-core libbsd0 libexpat1 libfontconfig1 libfontenc1 libfreetype6 libjpeg-turbo8 libpng16-16 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxrender1 multiarch-support ucf x11-common xfonts-75dpi xfonts-base xfonts-encodings xfonts-utils
          wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb
      - name: Create output directory
        run: mkdir output
      - name: Create PDF file from .md
        run: pandoc --from markdown --to pdf -t html --css ./styles.css --lua-filter ./pagebreak.lua -o output/cv.pdf --standalone index.md
      - uses: actions/upload-artifact@v1
        with:
          name: CV
          path: output/cv.pdf
