name: CI

on: [push]

permissions:
  contents: write

jobs:
  convert_to_html_for_pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Create output directory
        run: mkdir output && cp -r r output
      - name: Create HTML file from .md
        uses: docker://pandoc/core:2.9
        with:
          args: "--from markdown --to html --template ./templates/output.html -o output/index.html --standalone index.md"
      - name: Deploy to pages branch
        uses: JamesIves/github-pages-deploy-action@releases/v4.3.4
        with:
          BRANCH: gh-pages
          FOLDER: output
